print('Only Season 9 is included right now')
ifLore = input('Do you want to see Season 9 lore?(yes/no): ')

if (ifLore = 'yes'):
  print("On day 1, CreepYT got banned after joke betraying, and ECRACreepSplotion got the dragon egg. CreepYT got banned again on day 3. Creep made the Resin Mound, Ancient Debri Pond, and Temperature Graph Spawn. CreepYT actually left BloodShots and is going rogue. CreepYT created an Orbital Strike Cannon. Division and Ennard are actively looking for the Orbital built by CreepYT.")
  
ifVideos = input('Do you want to see Season 9 videos in chronological order?(yes/no): ')

if (ifVideos = 'yes'):
  print('CreepSplotion: The First Day')
  print('ReapSplotion: A New Season')
  print('Ennard: WTF')
  print('CreepYT: 5 Minutes')
  print('CreepSplotion: The Race For The Dragon Egg')
  print("CreepSplotion: It Didn't Work")
  print('CreepYT: REVIVED')
  print('CreepYT: The Nether')
  print('Ennard: Peace')
  print('Division: Peace')
  print('CreepYT: I Hate This')
  print('CreepYT: So Called Friends')
  print('CreepSplotion: CreepSpawn')
  print('CreepYT: My Evil Plan')
  print('CreepYT: Succession')
  print('CreepYT: The First Fire')
  print('Division: CHOAS')
  print('Ennard: Peace?')
  print('CreepSplotion: Betrayal')
  print('Giggles: The First Week')

ifLive = input('Do you want to see Season 9 live streams in chronological order?(yes/no): ')

if (ifLive = 'yes'):
  print('CreepSplotion: The First Day | 10 hours')
  print('ReapSplotion: The First Day | 6 hours')
  print('Ennard: The First Day | 9 hours')
  print('Division: The First Day | 27 hours')
  print('CreepYT: The First Day | 8 minutes')
  print('CreepYT: Banned Again | 3 hours')
  print('CreepYT: Grind | 3 hours')
  print('CreepYT: No | 3 hours')
  print('CreepYT: Building & Destruction | 19 hours')
  print("CreepYT: They're On | 3 hours")
  print("CreepYT: Fun Fun Fun | 10/14/25 | 6 hours")
  print("Ennard: Finding The Orbital #1 | 10/14/25 | 9 hours")
  print("Division: Finding The Orbital #1 | 10/14/25 | 13 hours")
  print("Giggles: Building A Base | 10/14/25 | 4 hours")
