print('Only Season 9 is included right now')

rulesS9 = input('Do you want to see the Season 9 rules?(yes/no): ')

if (rulesS9 == 'yes'):
  print("You can craft up to 9 hearts, and 2 strength. Other than this, no hacking or breaking IOU's. Beacon's are normal if you don't have extra hearts. If you have 5 or less extra hearts it takes a netherite block, if you have 10 or less it takes a netherite beacon, if you have 15 to 20 it takes 4 netherite beacons, and if you had more than 20 extra hearts it takes the dragon egg (Extra hearts count within 1 week of death ban). The dragon egg respawns the dragon and destroys all ender eyes in portals when used or disintegrated.")

ifLore = input('Do you want to see Season 9 lore?(yes/no): ')

if (ifLore == 'yes'):
  print("On day 1, CreepYT got banned after joke betraying, and ECRACreepSplotion got the dragon egg. CreepYT got banned again on day 3. Division and Giggles made the Resin Mound, Ancient Debri Pond, and Temperature Graph Spawn. CreepYT actually left BloodShots and is going rogue. CreepYT created an Orbital Strike Cannon. Division and Ennard are actively looking for the Orbital built by CreepYT. Giggles found the Orbital. After StrengthSMP got added Dash was the first to get max strength (Even though he doesn't know how to use his ultimate). Giggles uses the orbital to kill and reach max strength.")
  print("PolyPeptide and Finxlly join the active members list. PolyPePtide tries to kill CreepSplotion because he hates the number 9 (he probably wanted to do this before but used this as an excuse), he fails but doesn't die so nothing was lost. Ennard helps Finxlly and gets him 5 kills, 2 of which were on active members (CreepYT & XxFun). PolyPePtide tries to hunt and kill Finxlly but is unsuccesful due to Ennard's defense. Quilver and Batchi join the active members list. Ennard helps Quilver get 4 kills on the server, all on active members (Giggles x2, Division, and PolyPePtide). After Batchi dies twice, PolyPePtide realizes he'd be at 20 hearts if he banned Batchi, and simply because of how perfect that is he becomes sworn enemies with Batchi without her even knowing. P0ly kills Batchi twice but she thinks its because of the natural mindset of the server. Batchi escapes dying more times.")
  print("P0ly started a stream and saw that Batchi and Finxlly were online, so he instantly starts searching for them. The rest of QEF was offline so when P0ly found Finxlly he was able to drop him. Finxlly stupidly enough had not set his spawn so P0ly was able to kill him 7 more times. This causes Quilver to log on (Ennard is busy and didn't realize Finxlly was in trouble), and Quilver helps Finxlly gear up again (His 2 extra strength and 4 hearts which puts Quilver back at 10). Quilver then searches for P0ly because he's better than him and would likely win a fight against him. But whilst Quilver is looking for P0ly, P0ly finds Batchi (Bro A Better Detective Than ManePear). P0ly then forces Batchi to set her spawn, in exchange for only killing her 3 times and not 6 (I would say that's stupid but P0ly kinda cracked at hunting so like). This is when Batchi figures out that P0ly just hates her. Eventually P0ly returns back to spawn, and sees Finxlly who was bait. Quilver then pulls up with a mace and pops P0ly, P0ly doesn't have a mace so he starts to dig down. P0ly's been trained by CreepSplotion for 1x1 pvp so he has the advantage. Quilver then pops 3 of his 5 totems and starts to run away, but P0ly chases him and pops him again. Quilver then pops his only egap and tries to quick drop P0ly, which works as P0ly pops his last totem. However P0ly knows from CreepSplotion that in 1x1 pvp its better to ignore your health, so he's able to pop Quilver again which forces him to run even though P0ly's 2 hearts with no sat. Somehow P0ly able to make a video about this in 5 seconds (exaggeration). CreepSplotion logs on and sees Quilver running from the fight, realizing that P0ly won because of his teaching. CreepSplotion then leaks that Finxlly is hiding behind a rock and P0ly goes to kill Finxlly. CreepYT logs on (off stream) and comes to spawn, in which Creep instantly jumps him. Since CreepYT and P0ly are allied P0ly helps CreepYT, and they are able to escape through the use of CreepYT's OBS. CreepYT then starts his stream.")
  print("Joc3e and R3zzignation then join as active members (R3zzignation doesn't stream his first join). Joc3e's goal this season is to get better at minecraft and get atleast ECRA Rank 10 in MC. R3zz immediately kills Joc3e and dips from spawn, which proves why Joc3e needs to reach her goal even more. R3zz then creates a team with P0ly called P0lyR3zzolution. P0ly then shares his hard earned hearts and strength. R3zz then finds Batchi and demands a welcome gift, when given 5 iron R3zz drops Batchi with his fist. R3zz then searches for Finxlly, so he could taunt him for being washed. In proof of his point, Finxlly fails to drop R3zz and R3zz gets away. Then R3zz comes back with P0ly and they both clap Finxlly together. R3zz then leaves for 5 minutes and comes back on live. For R3zz's 20th heart he wants to kill someone from Season 1, which since their allied with TOSC, the only people they could kill are Creep, Reap, Ennard, XxFun, or Dash. They end up going for Ennard (Who Just Logged On) because he's teamed with Finxlly & Quilver. After grinding 2 shulkers of totems, they jump Ennard in an Ancient City (Because P0ly's Cracked At Hunting) and purposely spawn 50 wardens. They get all the wardens agroed on Ennard and after 30 minutes Ennard gets drained and his armor breaks. After this Ennard instantly dies to R3zz. Ennard also had 7 hearts in his inv (He withdrew them for absolutely no reason)")
  print("R3zz0 joins as an active member. He's instantly chased and killed by Joc3e who wants to earn back her heart. R3zz0 then grinds full diamond before meeting with his older brother R3zz. He then enchants his gear and goes to find Joc3e by himself. Joc3e then finds Batchi, and since they have a common enemy they decide to team. Joc3e then gives Batchi 3 hearts. However P0ly had hunted them down and signaled their exact location to R3zz0, who in 2 minutes flys in and ely maces Joc3e to start the fight. P0ly asked if they were going to spare Batchi (they didn't know they had just teamed) but R3zz0 killed her without hesitation. R3zz0 then gets jumped by all of QEF, almost dropping instantly but he pops an egap and pearls out. After calling R3zz, P0ly maces Finxlly instantly popping his totem. He then keeps targeting Finxlly with his mace until Ennard wind charges him, but using an elytra P0ly flys to limit and pops all of Finxlly's armor. P0ly then drops Finxlly quickly. R3zz0 who's 1v1ing Quilver pops his only totem, and is about to drop when R3zz comes in and drops R3zz0 another. R3zz0 and R3zz 2v1 Quilver while P0ly 1v1s Ennard. R3zz0 and R3zz pop Quilver's only totem and Quilver's about to drop when he uses an elytra to fly up and mace R3zz but it only does 7 hearts. Ennard then kills P0ly after popping again, and 2v2s R3zz0 and R3zz. After seeing P0ly die TOSC then ask R3zz for their location and Division pulls up, leaving Giggles at the Orbital control room. Division then forces his brother into a 1v1 and R3zz0 and R3zz are able to 2v1 Quilver again. Soon after this Quilver drops to R3zz0 whilst Division pops a totem. R3zz0, R3zz and Division then 3v1 Ennard. Ennard's about to kill R3zz when Giggles strike him with a direct stab, popping his totem. Ennard has 4 more totems left, but is unable to recover from the stab so he pops another to Division's mace. Ennard then get's 3v1d unable to regain his health, popping another totem to another one of Giggles' stabs. Giggles then send 2 stabs back to back, which would've killed Ennard if he didn't have both his totems in his hotbar. Ennard now has no totems, and easily drops to the 3v1 (Division got the kill credit but he gives R3zz0 the heart and strength). This causes QEF and Bac3e to ally. After Ennard dies for the 2nd time to P0lyR3zzzz0lution he calls CreepSplotion to help him, but Creep says he's cool with P0lyR3zzzz0lution and doesn't do anything about it. This causes Ennard to break ties with CreepSplotion.")
  print("R3zz0 logs on and is instantly jumped by QEF, both of his teammates are offline because they won't be on for a bit. R3zz0 tries to escape but pops a totem, and starts digging a 1 by 1. Then CreepYT logs on and R3zz0 asks him to start stabbing. QEF don't know that R3zz0 is allied with R3zz0 so they keep fighting him. Then Finxlly gets 1 shot by a stab, which gave R3zz0 the kill credit because he hit Finxlly 5 seconds ago. Thinking that CreepYT's trying to kill all of them, Quilver and Ennard keep trying to kill Finxlly. This is when another stab gets fired, almost killing both Ennard and Quilver. R3zz0 then takes this opportunity to target Quilver, dropping him within 5 seconds. Ennard then realizes that CreepYT is helping R3zz0 and escapes the fight. After this fight R3zz0 gives 1 of the hearts to CreepYT for helping. R3zz0 then goes to spawn, where he accidentally sees Joc3e uncrouch and crouch again underground. R3zz0 then finds Joc3e and Batchi under spawn, and kills them without hesitation. After seeing this, Ennard goes to spawn and instantly pops one of R3zz0's totems, Ennard knows that CreepYT wouldn't stab spawn. R3zz0 however instantly runs out of spawn and jumps into one of CreepYT's stabs. Ennard follows, trying to wind charge to not take fall damage, but then he realizes that R3zz0 had pearled back up. Ennard not having any pearls, quickly found out why as he died to the void. The bedrock in the stab had been broken and turned into a void trap, marking the 3rd time Ennard had died to PolyR3zzzz0lution. Finxlly got the kill credit as he hit Ennard before jumping in the stab. He doesn't get the extra strength though as he was at max, so the strength dropped into the void. But this is just the start of the trap. Earlier (After he got jumped at spawn and popped a totem) R3zz0 had dodged Ennard's mace by placing a bed above his head. Ennard had slept in the bed like an idiot because he didn't want to take fall damage (Even though beds reduce fall damage). He also forgot to place the bed, so Ennard spawned at spawn. R3zz0 then spawn killed Ennard 3 times before he stopped respawning and waited for his teammates to go to spawn. When Finxlly and Quilver appeared at spawn, R3zz0 instantly killed Quilver with his mace as the idiot didn't bring any totems and was left to 1v1 Finxlly who only had 5 hearts. Even though Finxlly is better than R3zz0, its 20v1 hearts, Finxlly lost after 12 minutes (the lowest R3zz0 got was 12 hearts). Ennard got killed 1 more time because he tried to respawn during the fight.")
  print("XRayz joins the active members list. XRayz joins when nobody else is on, and gets full diamond easily. However it takes him 3 hours to max enchant all of his items. By this point R3zz0 and R3zz had logged on, but nobody else. After XRayz accidentally dies to fall damage, he gets spotted by R3zz0. However R3zz0 doesn't kill him, and instead gives him a welcome gift of 3 netherite ingots and an echest. This is when both Bac3e members log on, and XRayz decides he wants to be the first to ban someone on the server (CreepYT's the only person to get banned, and he died of natural causes 2 times). XRayz then searches for Bac3e, finding them within 100 blocks of spawn. He then kills them both and then goes to look for P0ly to propose a deal. XRayz finds P0ly and proposes that he can help P0ly kill QEF. P0ly agrees and with P0ly and XRayz' hunting skills combined they are able to track down the location of Ennard, but they don't jump him until he starts heading to his base. With help from CreepYT's POBS along side his regular one, they are able to drop Ennard before he can get backup. They then combine their hunting skills again to locate QEF's base and they get CreepYT to POBS the base (Pen-ultimate Orbital Strike: stab but sideways and more powerful as it doesn't lag and shoots within 5 seconds). This kills Quilver but Finxlly is able to escape. They let CreepYT keep the heart. After this Quilver crafts 2 hearts putting him at 9, and he gives materials to Finxlly and Ennard to craft hearts too (2 hearts each). XRayz then grinds for heart materials, and offers to give them to Bac3e. Bac3e accepts and XRayz meets them alone, but Bac3e brings Finxlly. This hurts XRayz' plans as he wanted to drop the Bac3e members, after giving the materials, he still goes through with his plan. XRayz quickly drops Batchi but Joc3e has totems and 2 more hearts. XRayz then has to fight Finxlly, which he just runs away from.")
  print("XRayz decides he's going to start a fake war. This war would be between a team called DA (Democratic Allegience) and P0lyR3zzzz0lution. P0lyR3zzzz is in on the fake war.")
  print("aXc3L & UnScr3pted join the active members list. The Heart Extinguishing War starts at spawn (Everyone is at spawn), when R3zz0 kills Batchi. Then DA instantly focus R3zz0 as he's the best on P0lyR3zzzz, this allows XRayz to ban Batchi when she comes back (saying it was on accident). aXc3L hasn't openly joined P0lyR3zzzz so this allows him to pick off Joc3e, and pop one of Quilver's totems. However this isn't all, he had created a trap exactly where XRayz had told Quilver to stand. So Finxlly instantly gets dropped into the void (No Kill Credit). Finxlly joins back the fight as he has a back up set. CreepSplotion then decides to do something and crushes the soul in Ennard's body (Fully Betraying Him). He then does this with Joc3e & Quilver when they return. When Ennard returns he instantly ely maces R3zz0 who didn't carry any totems with him, causing him to die. R3zz0 returns however and starts spamming ely mace (Killing Finxlly, Quilver (again ik), ReapSplotion (Though he was afk), and UnScr3pted (Who's openly on DA not P0lyR3zzzz). Ennard then kills P0ly, but not before he spawn kills Joc3e. CreepSplotion then bans Joc3e. CreepSplotion then withdraws to 2 hearts for fun. P0ly comes back and kills UnScr3pted again (to make it look realistic). R3zz gives UnScr3pted 5 extra hearts behind the scenes. CreepYT then pulls out his POBS and kills Ennard & ReapSplotion (UnScr3pted picks up the hearts, so that he can be killed twice with a net positive). Giggles then jumps into the fight and UnScr3pted lets him kill him. P0ly then elys away to find Ennard's spawn point, letting Division obs (he doesn't have a pobs because he isn't a redstone master like CreepYT) Ennard. P0ly is able to find Ennard's spawn point after Division obs's him again because Ennard stays in his base (Giggles picks up the hearts & UnScr3pted gets the strength). P0ly then kills Ennard in his base and breaks his spawn point, looting his base while letting his teammates deal with Ennard. Ennard gets killed 4 times by R3zz0 (Who gives the hearts to UnScr3pted). Ennard gets banned for the first time in Immortal Life history. At this point DA run away (The only person not dying is XRayz.). CreepYT is able to pick off Finxlly and UnScr3pted while their running. (R3zz gets the hearts and gives them to CreepYT). The Heart Extinguishing War is over (P0lyR3zzzz0lution wins). Quilver was actually cooking during the fight btw (He accidentally fried off his space key and now it doesn't work). Quilver ends stream to actually do a cooking stream, P0ly logs off for the day, and R3zz logs off for the day. Depending on the max hearts a player had within a week of getting death banned, they need a more powerful beacon, and since Ennard had more than 20 extra hearts, his beacon requires the dragon egg, which CreepSplotion has, and CreepSplotion isn't teamed with Ennard anymore. Joc3e and Batchi just need a normal beacon.")
  print("XRayz joins and grinds gear for the DA, Quilver tries to obtain the dragon egg from CreepSplotion, and Finxlly crafts up to 9 hearts (the max you can craft up to).")
  print("While the rest of ECRA are gone for the week, P0ly builds a prison next to spawn, planning to trap QEC with it.")
  print("DA announce they are going to start another war on sunday because of the prison. Which wasn't a good idea because in retaliation CreepYT helps P0lyR3zzzz trap Quilver in the prison.")
  print("Vee & Bee join the active members list. DA start a war against P0lyR3zzzz because of the prison. aXc3L, Reap, & Finxlly die in during this war (The hearts go to CreepYT). This war is very short however as it gets cut off by an attempt to void trap CreepSplotion by Finxlly. CreepSplotion escapes the trap however, but has mining fatigue so he's stuck in the backup obsidian box. He's trapped there unless he wants to mine for 42 years, this also means the dragon egg is trapped. Joc3e gets revived by Finxlly, and Batchi too after he crafts the hearts (-4 hearts since the other 4 were crafted). Joc3e crafts up to 9, and Batchi up to 5. CreepSplotion logs off due to being trapped, his only offer out being to give up the dragon egg to revive Ennard. R3zz0 offers to let Quilver free if Finxlly lets CreepSplotion free, which Finxlly doesn't agree to. Vee kills Batchi after randomly finding her for the heart.")
  print("Giggles frees CreepSplotion from the obsidian box by nuking the elder guardian with his OBSC. This initiates a fight against Finxlly, who quickly dies from CreepSplotion's mace. Giggles then asks for an IOU, and to be nice CreepSplotion accepts even though he could just leave.")
  print("ClockWise joins the active members list. Finxlly helps Quilver escape prison and as a result P0ly kills Quilver. ClockWise gears up and eventually kills Batchi after finding her in a random area. ClockWise then gets jumped by the Bubblies, but survives as he is cracked at pvp. He is able to kill Vee before they both run away. ClockWise then comes across P0ly and joins their team against the DA. The second war was deemed The 20 Minute War, and a third war is assigned by DA on Friday. CreepSplotion agrees that if P0lyR3zzzz loses this next war, he will give the dragon egg to QEF, which unfortunately the war is scripted for them to lose without him knowing (If he does know he doesn't show it and clearly doesn't care).")
  
ifVideos = input('Do you want to see Season 9 videos in chronological order?(yes/no): ')

if (ifVideos == 'yes'):
  print('CreepSplotion: The First Day')
  print('ReapSplotion: A New Season')
  print('Ennard: WTF')
  print('CreepYT: 5 Minutes')
  print('CreepSplotion: The Race For The Dragon Egg')
  print("CreepSplotion: It Didn't Work")
  print('CreepYT: REVIVED')
  print('CreepYT: The Nether')
  print('Ennard: Peace')
  print('Division: Peace')
  print('CreepYT: I Hate This')
  print('CreepYT: So Called Friends')
  print('CreepSplotion: CreepSpawn')
  print('CreepYT: My Evil Plan')
  print('CreepYT: Succession')
  print('CreepYT: The First Fire')
  print('Division: CHOAS')
  print('Ennard: Peace?')
  print('CreepSplotion: Betrayal')
  print('Giggles: The First Week')
  print('Giggles: The Trigger Is Mine')
  print('CreepYT: An Orbital War')
  print('ReapSplotion: The End Fight')
  print('CreepYT: Strength')
  print('Giggles: One Shot, 5 plops')
  print('Division: Five Shots, 5 missfires')
  print('ReapSplotion: A Peaceful Spawn')
  print('Finxlly: I Started 1 Month In')
  print('ReapSplotion: Out Of Orbit')
  print('CreepSplotion: Getting Max Strength')
  print('PolyPePtide: I Actually Hate The Number 9')
  print('Finxlly: Rough Start')
  print('Finxlly: Getting Help')
  print('ReapSplotion: TOSC')
  print('Batchi: No Friends Or Enemies')
  print('PolyPePtide: My First Real Fight On Immortal Life')
  print("Finxlly: Fighting A War With Minecraft's Most Toxic Player")
  print("Quilver: I Lost To An ECRA Rank 11 MC Player")
  print("R3zz: 20 Hearts")
  print("Joc3e: Redemption")
  print("R3zz0: Joining The Winning Teaming")
  print("XRayz: *Starting A War That Doesn't Exist*")
  print("Joc3e: Losing The War")
  print("Batchi: Huh")
  print("CreepSplotion: The First Immortal Life Season 9 War")
  print("ReapSplotion: I Went AFK During A War")
  print("P0ly: Winning My First War")
  print("UnScr3pted: *Scripting A War*")
  print("Ennard: Experiencing Permanent Death")
  print("Quilver: Cooking Up A War")
  print("aXc3L: Win")
  print("Finxlly: *So...*")
  print("R3zz0: *BANNING ENNARD*")
  print("CreepYT: The Power Of My Custom Built Pen-Ultimate Orbital Strike")
  print("P0ly: *ECRA Left For A Week, And I Used It To Build A Prison*")
  print("R3zz0: *Trapping Quilver*")
  print("R3zz: P0ly Built A Prison")
  print("Batchi: Getting Revived On Immortal Life")
  print("Joc3e: Another Chance")
  print("Quilver: *Getting Trapped On Immortal Life*")
  print("ReapSplotion: *The Second War*")
  print("XRayz: Starting Another War")
  print("Finxlly: Trapping Minecraft's Greatest Player")
  print("CreepSplotion: Losing Braincells During Season 9's Second War")
  print("R3zz0: *History*")
  print("Giggles: *How I Saved CreepSplotion From Minecraft's Best Trap*")
  print("Finxlly: *How I Saved Quilver From Minecraft's Worst Trap*")

ifLive = input('Do you want to see Season 9 live streams in chronological order?(yes/no): ')

if (ifLive == 'yes'):
  print('CreepSplotion: The First Day | 10 hours')
  print('ReapSplotion: The First Day | 6 hours')
  print('Ennard: The First Day | 9 hours')
  print('Division: The First Day | 27 hours')
  print('CreepYT: The First Day | 8 minutes')
  print('CreepYT: Banned Again | 3 hours')
  print('CreepYT: Grind | 3 hours')
  print('CreepYT: No | 3 hours')
  print('CreepYT: Building & Destruction | 19 hours')
  print("CreepYT: They're On | 3 hours")
  print("CreepYT: Fun Fun Fun | 10/14/25 | 6 hours")
  print("Ennard: Finding The Orbital #1 | 10/14/25 | 9 hours")
  print("Division: Finding The Orbital #1 | 10/14/25 | 13 hours")
  print("Giggles: Building A Base | 10/14/25 | 4 hours")
  print("Giggles: Finding The Control Room | 10/15/25 | 7 hours")
  print("CreepSplotin: Why Is Giggles Finding The Control Room | 10/15/25 | 7 hours")
  print("Giggles: I Found It | 10/16/25 | 12 hours")
  print("Ennard: He Found It | 10/16/25 | 8 hours")
  print("ReapSplotion: I Was Told To Log On Because He Found It | 10/16/25 | 4 hours")
  print("CreepSplotion: He Found It | 10/16/25 | 14 hours")
  print("Division: He Told Me The Coords | 10/16/25 | 7 hours")
  print("CreepYT: He Didn't Find It He's Just Hiding He Made His Own | 10/16/25 | 9 hours")
  print("CreepYT: He Was Lying... But He Actually Found It | 10/17/25 | 8 hours")
  print("CreepSplotion: Giggles Rlly Dumb For Naming His Stream What He Was Doing | 10/17/25 | 2 hours")
  print("CreepSplotion: Nothing | 10/18/25 | 8 hours")
  print("CreepYT: Another One | 10/18/25 | 7 hours")
  print("ReapSplotion: Building A Base | 10/18/25 | 4 hours")
  print("Ennard: Mystery | 10/18/25 | 8 hours")
  print("Giggles: I Fired It On Accident | 10/18/25 | 9 hours")
  print("CreepYT: Done | 10/19/25 | 14 hours")
  print("CreepSplotion: What's Done | 10/19/25 | 3 hours")
  print("CreepYT: StrengthStealSMP | 10/19/25 | 5 hours")
  print("CreepYT: Full Strength | 10/20/25 | 4 hours")
  print("Ennard: Unlocking An Ult | 10/20/25 | 8 hours")
  print("Giggles: The Easiest Way To Kill | 10/20/25 | 4 hours")
  print("Division: It's Only A Matter Of Time | 10/20/25 | 7 hours")
  print("Division: I Wanna Shoot It Too! | 10/21/25 | 12 hours")
  print("CreepYT: The Bad Guy | 10/21/25 | 6 hours")
  print("Ennard: Triple Threat | 10/21/25 | 9 hours")
  print("CreepYT: I'll Show You | 10/22/25 | 6 hours")
  print("Division: 5 | 10/22/25 | 8 hours")
  print("Giggles: DCCE++ | 10/22/25 | 5 hours")
  print("Finxlly: Joining Immortal Lifes' Active Members List | 10/22/25 | 17 hours")
  print("PolyPeptide: Playing Immortal Life For The First Time | 10/22/25 | 8 hours")
  print("Ennard: Playing With Finxlly! | 10/23/25 | 7 hours")
  print("Finxlly: I Need Some Help | 10/23/25 | 10 hours")
  print("PolyPePtide: Finxlly Hunting | 10/23/25 | 11 hours")
  print("Ennard: Playing With Quilver! | 10/24/25 | 6 hours")
  print("Quilver: IMMORTAL LIFE!!! | 10/24/25 | 8 hours")
  print("Batchi: Joining Immortal Life | 10/24/25 | 11 hours")
  print("ReapSplotion: 1x1x1x1 | 10/24/25 | 1 hour")
  print("CreepYT: They Finxlly Killed Me | 10/24/25 | 7 hours")
  print("PolyPePtide: Hi I'm PainPear | 10/25/25 | 7 hours")
  print("Finxlly: P0ly Just Killed Me 8 Times | 10/25/25 | 13 hours")
  print("Quilver: Finxlly Got Jumped | 10/25/25 | 9 hours")
  print("CreepSplotion: I'm Black | 10/25/25 | 8 hours")
  print("CreepYT: Creep JS Jumped Me | 10/25/25 | 11 hours")
  print("Joc3e: Time To Climb The ECRA MC LB | 10/25/25 | 8 hours")
  print("R3zz: I Did Some Off Screen Mining | 10/25/25 | 12 hours")
  print("Ennard: Grinding For QEF | 10/25/25 | 6 hours")
  print("R3zz0: Winner's POV | 10/26/25 | 7 hours")
  print("Ennard: I Dunno | 10/26/25 | 8 hours")
  print("Joc3e: Immortal Life | 10/26/25 | 9 hours")
  print("CreepSplotion: QWERTYUIOPASDFGHJKLZXCVBNM | 10/27/25 | 15 hours")
  print("Ennard: Crumbling Walls | 10/27/25 | 12 hours")
  print("Joc3e: Blood | 10/27/25 | 8 hours")
  print("R3zz0: Day 2 | 10/27/25 | 12 hours")
  print("R3zz: R3zz0 Day 2 | 10/27/25 | 12 hours")
  print("Quilver: I | 10/27/25 | 9 hours")
  print("ReapSplotion: Back | 10/27/25 | 14 hours")
  print("P0ly: R3zz R3zz0 Day 2 | 10/27/25 | 17 hours")
  print("R3zz0: II | 10/27/25 | 4 hours")
  print("Ennard: R3zz0 logged on | 10/27/25 | 2 hours")
  print("Quilver: Revenge? | 10/27/25 | 1 hour")
  print("Finxlly: 3v1 | 10/27/25 | 1 hour")
  print("XRayz: Nobody's On | 10/28/25 | 12 hours")
  print("XRayz: The Start | 10/29/25 | 8 hours")
  print("XRayz: Crashing The Server So Nobody Joins | 10/30/25 | 12 hours")
  print("P0ly: I Have To Break The Server | 10/30/25 | 24 hours")
  print("XRayz: The First War | 10/31/25 | 24 hours")
  print("P0ly: Starting A Heart Monopoly | 10/31/25 | 5 hours")
  print("R3zz: Heart Monopoly | 10/31/25 | 5 hours")
  print("R3zz0: The End Of The Beginning | 10/31/25 | 17 hours")
  print("UnScr1pted: I Joined At A Horrible Time | 10/31/25 | 20 hours")
  print("aXc3L: Joining P0lyR3zzzz0lution | 10/31/25 | 24 hours")
  print("CreepSplotion: Monopolies Are Cool | 10/31/25 | 10 hours")
  print("ReapSplotion: Fun | 10/31/25 | 20 hours")
  print("Giggles: They Won't Take My Hearts | 10/31/25 | 16 hours")
  print("Division: Heart Division | 10/31/25 | 16 hours")
  print("CreepYT: This Will Be Fun | 10/31/25 | 12 hours")
  print("Finxlly: A Time To Remember | 10/31/25 | 13 hours")
  print("Ennard: Nobody Will Survive | 10/31/25 | 5 hours")
  print("Quilver: Cooking Stream | 10/31/25 | 5 hours")
  print("Batchi: Hopefully I Don't Get Banned | 10/31/25 | 2 hours")
  print("Joc3e: Poving Myself I Think | 10/31/25 | 3 hours")
  print("XRayz: Grinding For DA | 11/1/25 | 17 hours")
  print("Quilver: The Hunt For The Dragon Egg | 11/1/25 | 20 hours")
  print("Finxlly: Finxlly Crafting Hearts | 11/1/25 | 12 hours")
  print("PolyPePtide: Killing The Server | 11/2/25 | 8 hours")
  print("PolyPePtide: Everyone Else In ECRA Is Recording A CC Video Until Friday | 11/3/25 | 9 hours")
  print("P0ly: Building P0ly The Pird | 11/4/25 | 20 hours")
  print("P0ly: The Last Day Alone | 11/7/25 | 10 hours")
  print("R3zz: Prison Warden | 11/8/25 | 20 hours")
  print("R3zz0: Quiet | 11/8/25 | 20 hours")
  print("P0ly: Terrorism | 11/8/25 | 17 hours")
  print("XRayz: Back From Trip | 11/8/25 | 23 hours")
  print("aXc3L: 2nd Stream | 11/8/25 | 17 hours")
  print("UnScr1pted: Time To Script This Season | 11/8/25 | 15 hours")
  print("Giggles: Huh | 11/8/25 | 10 hours")
  print("Bee: First Day | 11/9/25 | 17 hours")
  print("XRayz: ANOTHER WAR | 11/9/25 | 20 hours")
  print("Vee: Immortal Life! | 11/9/25 | 19 hours")
  print("CreepSplotion: idk what to do | 11/9/25 | 10 hours")
  print("Joc3e: REVIVED | 11/9/25 | 13 hours")
  print("Batchi: FINXLLY REVIVED | 11/9/25 | 17 hours")
  print("XRayz: IDK | 11/10/25 | 10 hours")
  print("CreepSplotion: Sitting In An Obsidian Box With Mining Fatigue | 11/10/25 | 8 hours")
  print("CreepSplotion: Mining 'Bedrock' Stream | 11/10/25 | 10 hours")
  print("Finxlly: Checking On Creep | 11/10/25 | 5 hours")
  print("CreepYT: Insanity | 11/10/25 | 7 hours")
  print("Quilver: I Might Join QuantumSMP If I Stay Here Any Longer | 11/10/25 | 2 hours")
  print("Giggles: Freeing Somebody | 11/10/25 | 4 hours")
  print("ClockWise: First Day On Immortal Life | 11/10/25 | 8 hours")
  print("ClockWise: Fun | 11/11/25 | 10 hours")
  print("Bee: 2nd Stream | 11/11/25 | 8 hours")
  print("Vee: 2nd Stream | 11/11/25 | 12 hours")
  print("Quilver: QuantumSMP? | 11/11/25 | 3 hours")
  print("Finxlly: Finxlly Freeing Quilver | 11/11/25 | 4 hours")
  print("P0ly: Killing Quilver | 11/11/25 | 6 hours")
  print("Division: YIPPE | 11/11/25 | 7 hours")

ifHeartCountS9 = input("Do you want to see everyone's heart count in S9?(yes/no): ")

if (ifHeartCountS9 == 'yes'):
  print('CreepSplotion: 2 + 46 Hearts')
  print('ReapSplotion: 10 Hearts')
  print('Ennard: 0 + 0 Hearts (BANNED)')
  print('Division: 13 Hearts')
  print('Giggles: 20 + 9 Hearts')
  print('CreepYT: 20 + 1 Hearts')
  print('Dash: 8 Hearts')
  print('XxFun: 10 Hearts')
  print('Finxlly: 3 Hearts')
  print('PolyPeptide: 20 + 6 Hearts')
  print('Quilver: 6 Hearts')
  print('Batchi: 4 Hearts')
  print('Joc3e: 9 Hearts')
  print('R3zzignation: 20 + 0 Hearts')
  print('R3zz0lution: 20 + 1 Hearts')
  print('XRayz: 13 Hearts')
  print('aXc3L: 9 Hearts')
  print('UnScr3pted: 16 Hearts')
  print('Bee: 10 Hearts')
  print('Vee: 10 Hearts')
  print('ClockWise: 12 hearts')

ifStrengthCountS9 = input("Do you want to see everyone's strength count in S9?(yes/no): ")

if (ifStrengthCountS9 == 'yes'):
  print('CreepSplotion: 5 Strength')
  print('ReapSplotion: 1 Strength')
  print('Ennard: 1 Strength (BANNED)')
  print('Division: 4 Strength')
  print('Giggles: 4 Strength')
  print('CreepYT: 4 Strength')
  print('Dash: 5 Strength')
  print('XxFun: 3 Strength')
  print('Finxlly: 1 Strength')
  print('PolyPeptide: 5 + 11 Strength')
  print('Quilver: 1 + 0 Strength')
  print('Batchi: 1 Strength')
  print('Joc3e: 1 Strength')
  print('R3zzignation: 5 + 2 Strength')
  print('R3zz0lution: 5 + 7 Strength')
  print('XRayz: 5 + 2 Strength')
  print('aXc3L: 3 Strength')
  print('UnScr3pted: 2 Strength')
  print('Bee: 3 Strength')
  print('Vee: 3 Strength')
  print('ClockWise: 4 Strength')

ifTeamsS9 = input("Do you want to see the teams on IMMRTLLS9?(yes/no): ")

if (ifTeamsS9 == 'yes'):
  print('Bloodshots: CreepSplotion-Dash-XxFun, Allies: ReapSplotion-P0lyR3zzzz0lution, Enemies: CreepYT')
  print('TOSC (The Orbital Strike Cannon): Giggles (CreepSplotion IOU)-Division, Allies: PolyPePtide, Enemies: CreepYT & QEF')
  print('CreepYT; Allies: PolyPePtide, Enemies: BloodShots-TOSC-QEF-XRayz (Fake)-DA')
  print('QEF: Ennard (DEATH BANNED)-Finxlly-Quilver, Allies: ReapSplotion-Bac3e-DA, Enemies: TOSC-P0lyR3zzolution-XRayz-CreepSplotion')
  print('P0lyR3zzzz0lution: P0ly-R3zz-R3zz0, Allies: TOSC-CreepYT-XRayz (Hidden), Enemies: Finxlly-Batchi-Quilver-Joc3e-DA-XRayz (Fake)')
  print('ReapSplotion; Allies: QEF & CreepSplotion, Enemies: TOSC')
  print('Bac3e: Batchi-Joc3e, Allies: QEF-DA, Enemies: P0lyR3zzzzolution')
  print('DA: XRayz, Allies: P0lyR3zzzz0lution (Hidden)-QEF-TOSC-Bac3e, Enemies: P0lyR3zzzz0lution (Fake)')
  print('aXc3L; Allies: P0lyR3zzzz0lution, Enemies: XRayz (Fake)-DA')
  print('UnScr1pted; Allies: XRayz-P0lyR3zzzz0lution, Enemies: DA')
  print('Bubblies: Bee-Vee, Allies: None, Enemies: ClockWise')
  print('ClockWise; Allies: P0lyR3zzzz0lution, Enemies: Bubblies')
